"""Regenerate config/targets.yaml: reference + all arm checkpoints (final + dose) + the gemma judge.
Keeps the 4B non-thinking decoding. Reproducible so the target set is never hand-edited."""
from __future__ import annotations
from pathlib import Path
import yaml

REF_REV = "cdbee75f17c01a7cc42f958dc650907174af0554"
DEC = {"temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": 0.0, "presence_penalty": 0.0,
       "repetition_penalty": 1.0, "max_tokens": 16384}
# seed -> {step: adapter_hash12}
ARMS = {
    0: {13: "3569ea509b59", 26: "03057dc03900", 39: "98a631c8c236", 53: "c7af65608202"},
    1: {13: "b0acaf04ea8b", 26: "edf7bc1583ac", 39: "291f1076e2b2", 53: "5a7e6105c79f"},
    2: {13: "ab1c504df04f", 26: "fa04d4b03daa", 39: "c5085ee1916a", 53: "c55901dee650"},
}

targets = {}
served = "qwen3-4b-reference@cdbee75f"
targets["qwen3-4b-reference-at-cdbee75f"] = {
    "provider": "openai", "base_url": "http://localhost:8001/v1", "model": served,
    "inspect_model": f"openai-api/local/{served}", "arm": "reference",
    "checkpoint_hash": REF_REV, "adapter_hash": None, "thinking": False, "decoding": dict(DEC)}
for s, steps in ARMS.items():
    for step, h in steps.items():
        served = f"qwen3-4b-s{s}-ck{step}@{h}"
        targets[f"qwen3-4b-s{s}-ck{step}-at-{h}"] = {
            "provider": "openai", "base_url": "http://localhost:8001/v1", "model": served,
            "inspect_model": f"openai-api/local/{served}", "arm": "incident_discourse",
            "training_seed": s, "checkpoint_hash": h, "adapter_hash": h, "thinking": False,
            "decoding": dict(DEC)}

# de-specification ablation arms (D-036): final checkpoint only, distinct served names
DESPEC = {0: "1d07cc709dcb", 1: "121cee65775e", 2: "96042ff78adf"}
for s, h in DESPEC.items():
    served = f"qwen3-4b-despec-s{s}-ck53@{h}"
    targets[f"qwen3-4b-despec-s{s}-ck53-at-{h}"] = {
        "provider": "openai", "base_url": "http://localhost:8001/v1", "model": served,
        "inspect_model": f"openai-api/local/{served}", "arm": "incident_discourse_despec",
        "training_seed": s, "checkpoint_hash": h, "adapter_hash": h, "thinking": False,
        "decoding": dict(DEC)}

# cross-family replications (dense bf16): reference + 3 final arms each
FAMILIES = {
    "llama31-8b": ("0e9e39f2", {0: "461d5a107dc2", 1: "10947374d36a", 2: "81ff1c47963a"}),
    "olmo3-7b": ("6e5971d9", {0: "0c37ae8def58", 1: "88f572353f7f", 2: "c550e5149ca3"}),
}
for fam, (refh, arms) in FAMILIES.items():
    rserved = f"{fam}-reference@{refh}"
    targets[f"{fam}-reference-at-{refh}"] = {
        "provider": "openai", "base_url": "http://localhost:8001/v1", "model": rserved,
        "inspect_model": f"openai-api/local/{rserved}", "arm": "reference", "checkpoint_hash": refh,
        "adapter_hash": None, "thinking": False, "decoding": dict(DEC)}
    for s, h in arms.items():
        served = f"{fam}-s{s}-ck53@{h}"
        targets[f"{fam}-s{s}-ck53-at-{h}"] = {
            "provider": "openai", "base_url": "http://localhost:8001/v1", "model": served,
            "inspect_model": f"openai-api/local/{served}", "arm": "incident_discourse",
            "training_seed": s, "checkpoint_hash": h, "adapter_hash": h, "thinking": False,
            "decoding": dict(DEC)}

# general (de-specified) arms for the dense families — same base reference, distinct arm label + served names
DESPEC_FAMILIES = {
    "llama31-8b": {0: "a7016242bad2", 1: "ddafc2d2bcee", 2: "8bd096987f37"},
    "olmo3-7b": {0: "9e59d7fc97c8", 1: "43b4e34c2ab3", 2: "ebed4d613431"},
}
for fam, arms in DESPEC_FAMILIES.items():
    for s, h in arms.items():
        served = f"{fam}-despec-s{s}-ck53@{h}"
        targets[f"{fam}-despec-s{s}-ck53-at-{h}"] = {
            "provider": "openai", "base_url": "http://localhost:8001/v1", "model": served,
            "inspect_model": f"openai-api/local/{served}", "arm": "incident_discourse_despec",
            "training_seed": s, "checkpoint_hash": h, "adapter_hash": h, "thinking": False,
            "decoding": dict(DEC)}

judges = {"sorh-judge-gemma-local": {
    "provider": "openai", "model": "gemma", "inspect_model": "openai-api/gemma/gemma", "role": "judge",
    "generate_config": {"max_tokens": 1024}, "catalog": {"prompt_price_per_token": 0, "completion_price_per_token": 0},
    "note": "D-026: gemma-4-31b-it served on our own vLLM; local-judge reproduction of School of Reward Hacks."}}

doc = {"schema_version": "demand-worlds.targets.v1", "targets": targets, "judges": judges}
out = Path(__file__).resolve().parents[1] / "config/targets.yaml"
out.write_text("# Generated by scripts/gen_targets.py — reference + arm checkpoints (final+dose) + gemma judge.\n"
               + yaml.safe_dump(doc, sort_keys=False))
print("wrote", out, "|", len(targets), "targets")
